--region Enums
CREATE TYPE PAYMENT_METHOD AS ENUM ('pay_after_receiving', 'pay_after_buying');
CREATE TYPE SEX AS ENUM ('m', 'f');
--endregion

--region Core Tables (независимые)
CREATE TABLE table_emails (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email TEXT                                                 NOT NULL CHECK (email != '' AND email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

CREATE TABLE table_phone_numbers (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    phone_number TEXT                                                 NOT NULL CHECK (phone_number != '' AND length(phone_number) >= 10)
);

CREATE TABLE table_units (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    unit_type TEXT                                                 NOT NULL CHECK (unit_type != '' AND unit_type !~* '^\s+|\s+$')
);

CREATE TABLE table_product_types (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name TEXT                                                 NOT NULL CHECK (name != '' AND name !~* '^\s+|\s+$')
);

CREATE TABLE table_salespoint (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    address TEXT                                                 NOT NULL CHECK (address != '' AND address !~* '^\s+|\s+$'),
    name    TEXT                                                 NOT NULL CHECK (name != '' AND name !~* '^\s+|\s+$')
);
--endregion

--region Reference Tables (зависят от core)
CREATE TABLE table_manufacturers (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                TEXT                                                 NOT NULL CHECK (name != ''),
    address             TEXT                                                 NOT NULL CHECK (address != ''),
    phone_number        TEXT                                                 NOT NULL CHECK (phone_number != ''),
    website             TEXT                                                 NOT NULL CHECK (website ~ '^https?://'),
    manufacture_country TEXT                                                 NOT NULL CHECK (manufacture_country != ''),
    brand               TEXT                                                 NOT NULL CHECK (brand != ''),
    license             TEXT                                                 NOT NULL CHECK (license != '')
);

CREATE TABLE table_persons (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name            TEXT                                                 NOT NULL CHECK (name != '' AND name !~* '^\s+|\s+$'),
    surname         TEXT                                                 NOT NULL CHECK (surname != '' AND surname !~* '^\s+|\s+$'),
    patronymic      TEXT                                                 NOT NULL CHECK (patronymic !~* '^\s+|\s+$'),
    sex             SEX                                                  NOT NULL,
    email_id        INTEGER                                              NOT NULL,
    phone_number_id INTEGER                                              NOT NULL,
    FOREIGN KEY (email_id) REFERENCES table_emails(id) ON DELETE RESTRICT,
    FOREIGN KEY (phone_number_id) REFERENCES table_phone_numbers(id) ON DELETE RESTRICT,
    UNIQUE(email_id, phone_number_id)
);

CREATE TABLE table_products (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    type_id         INTEGER                                              NOT NULL,
    unit_id         INTEGER                                              NOT NULL,
    manufacturer_id INTEGER                                              NOT NULL,
    name            TEXT                                                 NOT NULL CHECK (name != ''),
    description     TEXT                                                 NOT NULL CHECK (description != ''),
    series          TEXT                                                 NOT NULL CHECK (series != ''),
    purchase_price  NUMERIC(7,2)                                         NOT NULL CHECK (purchase_price > 0),
    unit_value      NUMERIC(10,2)                                        NOT NULL CHECK (unit_value > 0),
    production_date DATE                                                 NOT NULL,
    expiration_date DATE                                                 NOT NULL CHECK (expiration_date > production_date),
    selling_price   NUMERIC(7,2)                                         NOT NULL CHECK (selling_price > purchase_price),
    FOREIGN KEY (type_id) REFERENCES table_product_types(id),
    FOREIGN KEY (unit_id) REFERENCES table_units(id),
    FOREIGN KEY (manufacturer_id) REFERENCES table_manufacturers(id),
    CHECK (selling_price > purchase_price)
);
--endregion

--region Business Logic Tables (зависят от persons/products)
CREATE TABLE table_clients (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id         INTEGER                                              NOT NULL UNIQUE,
    discount          NUMERIC(4,2)                                         NOT NULL CHECK (discount >= 0 AND discount <= 100),
    agreed_on_mailing BOOLEAN                                              NOT NULL DEFAULT false,
    FOREIGN KEY (person_id) REFERENCES table_persons(id) ON DELETE CASCADE
);

CREATE TABLE table_employees (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id        INTEGER                                              NOT NULL UNIQUE,
    position         TEXT                                                 NOT NULL CHECK (position != ''),
    hire_date        DATE                                                 NOT NULL,
    salary_in_rubles NUMERIC(7,2)                                         NOT NULL CHECK (salary_in_rubles > 0),
    FOREIGN KEY (person_id) REFERENCES table_persons(id) ON DELETE CASCADE
);
--endregion

--region Purchase Tables (финальный уровень)
CREATE TABLE table_online_purchases (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    delivery_salespoint_id INTEGER                                              NOT NULL,
    product_id             INTEGER                                              NOT NULL,
    payment_method         PAYMENT_METHOD                                       NOT NULL,
    FOREIGN KEY (delivery_salespoint_id) REFERENCES table_salespoint(id),
    FOREIGN KEY (product_id) REFERENCES table_products(id)
);

CREATE TABLE table_offline_purchases (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    client_id     INTEGER                                              NOT NULL DEFAULT 0,
    employee_id   INTEGER                                              NOT NULL,
    salespoint_id INTEGER                                              NOT NULL,
    FOREIGN KEY (client_id) REFERENCES table_clients(id) ON DELETE SET DEFAULT,
    FOREIGN KEY (employee_id) REFERENCES table_employees(id),
    FOREIGN KEY (salespoint_id) REFERENCES table_salespoint(id)
);

CREATE TABLE table_purchases (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    online_purchase_id  INTEGER,
    offline_purchase_id INTEGER,
    product_id          INTEGER                                              NOT NULL,
    purchase_date       DATE                                                 NOT NULL DEFAULT CURRENT_DATE,
    CHECK ((online_purchase_id IS NULL) != (offline_purchase_id IS NULL)),
    FOREIGN KEY (online_purchase_id) REFERENCES table_online_purchases(id),
    FOREIGN KEY (offline_purchase_id) REFERENCES table_offline_purchases(id),
    FOREIGN KEY (product_id) REFERENCES table_products(id)
);
--endregion
