CREATE TABLE table_manufacturers
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   TEXT NOT NULL,
    county TEXT NOT NULL
);

CREATE TABLE table_products
(
    id                         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id                    INT            NOT NULL,

    name                       TEXT           NOT NULL,
    product_type               TEXT           NOT NULL,
    price                      NUMERIC(10, 2) NOT NULL CHECK ( price > 0 ),
    cost_price                 NUMERIC(10, 2) NOT NULL,
    manufacturers_id           INT            NOT NULL,
    quantity_products_in_stock INT CHECK (!<0),
    FOREIGN KEY (manufacturers_id) REFERENCES table_manufacturers (id)

);

CREATE TABLE table_employee
(
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name               TEXT NOT NULL CHECK ( employee_name != '' ),
    employee_surname            TEXT NOT NULL CHECK ( employee_surname != '' ),
    employee_patronymic         TEXT NOT NULL CHECK ( employee_patronymic != '' ),
    employee_post               TEXT NOT NULL CHECK ( employee_post != '' ),
    employee_date_of_employment INT  NOT NULL CHECK ( employee_date_of_employment != 0 ),
    employee_sex                TEXT NOT NULL CHECK ( employee_sex != '' ),
    employee_salary             INT  NOT NULL CHECK ( employee_salary != 0 )
);

CREATE TABLE table_client
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       INT     NOT NULL,
    client_name       TEXT    NOT NULL CHECK ( client_name != '' ),
    client_surname    TEXT    NOT NULL CHECK ( client_surname != '' ),
    client_patronymic TEXT    NOT NULL CHECK ( client_patronymic != '' ),
    client_email      TEXT    NOT NULL CHECK ( client_email != '' ),
    client_phone      INT     NOT NULL CHECK ( client_phone != 0 ),
    client_sex        TEXT    NOT NULL CHECK ( client_sex != '' ),
    order_history     TEXT    NOT NULL CHECK ( order_history != '' ),
    discount          INT     NOT NULL CHECK ( discount = 0 or discount > 0 ),
    mailing_list      BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (employee_id) REFERENCES table_employee (id)

);

CREATE TABLE table_sale
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       INT            NOT NULL,
    product_id        INT            NOT NULL,
    client_id         INT            NOT NULL,

    sale_product_name TEXT           NOT NULL,
    sale_price        NUMERIC(10, 2) NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES table_employee (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id),
    FOREIGN KEY (client_id) REFERENCES table_client (id)
);

CREATE OR REPLACE FUNCTION quantity_products_in_stock()
    RETURNS TRIGGER AS $$
    BEGIN
    IF (SELECT quantity_products_in_stock
        FROM table_products
        WHERE id = NEW.product_id) < NEW.quantity THEN
        RAISE EXCEPTION 'Not enought stock for products %', NEW.product_id;
        END IF;
    UPDATE table_products
        SET quantity_products_in_stock =quantity_products_in_stock - NEW.quantity
        WHERE id = NEW.product_id;
    END;
    $$ LANGUAGE plpgsql;


CREATE TRIGGER before_insert_sales_orders_decrease_stock
    BEFORE INSERT
    ON table_sale
    FOR EACH ROW
EXECUTE FUNCTION quantity_products_in_stock();

