CREATE TABLE IF NOT EXISTS table_clients
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL CHECK ( first_name != '' ),
    patronymic TEXT,
    last_name  TEXT NOT NULL CHECK ( last_name != '' ),
    age        INT  NOT NULL CHECK ( age <= 0 ),
    sex        public.sex  NOT NULL
);


CREATE TABLE IF NOT EXISTS table_client_phone_numbers
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number_id INT REFERENCES table_clients (id),
    phone_number    TEXT NOT NULL CHECK ( phone_number LIKE '+7%' OR phone_number LIKE '8%' )
);


CREATE TABLE IF NOT EXISTS table_client_emails
(
    id                       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id                 INT REFERENCES table_clients (id),
    is_subscribed_newsletter BOOLEAN NOT NULL DEFAULT FALSE,
    email                    TEXT    NOT NULL CHECK ( email LIKE '%@%')
);
