CREATE TABLE IF NOT EXISTS table_employees
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL CHECK ( first_name != '' ),
    patronymic TEXT,
    last_name  TEXT NOT NULL CHECK ( last_name != '' ),
    position   public.position,
    hire_date  DATE NOT NULL,
    sex        public.sex  NOT NULL
);


INSERT INTO table_employees (first_name, patronymic, last_name, position, hire_date, sex)
VALUES ('Иван','Иванович','Иванов','SALES_ASSISTANT','2024-11-01','M')

\