CREATE TABLE IF NOT EXISTS table_salary_rates
(
    id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id             INTEGER NOT NULL REFERENCES table_employees (id),
    hourly_rate             NUMERIC(10, 2) CHECK ( hourly_rate >= 0 ),
    commission_percent      NUMERIC(5, 2) CHECK ( commission_percent >= 0 AND commission_percent <= 100 ),
    rate_action_begins_date DATE    NOT NULL,
    rate_action_ends_date   DATE
);


CREATE TABLE IF NOT EXISTS table_monthly_payments
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id           INTEGER NOT NULL REFERENCES table_employees (id),
    payment_for_month     DATE    NOT NULL,
    hours_worked          NUMERIC(6, 2),
    payment_for_hours     NUMERIC(12, 2),
    total_sales           NUMERIC(12, 2),
    commission_earned     NUMERIC(12, 2),
    total_payment         NUMERIC(12, 2),
    actually_payment_date DATE
);








